step-1:import libraries

In [86]:
import  numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.simplefilter("ignore")

LOADING THE DATA SET

In [87]:
df = pd.read_csv(r"C:\Users\Kishore\Downloads\netflix_movies_tv_shows_raw_task1_8900_rows.csv")
df

,show_id,type,title,director,country,date_added,release_year,rating,listed_in,duration,language,description
0,s5219,TV Show,Red Notice,Anurag Kashyap,NaN,2019-12-08 20:01:50,1998.0,TV-G,Comedies,2 Seasons,NaN,Description for title 5219
1,s5678,Movie,Lagaan,Rian Johnson,South Korea,2024-09-23 13:00:57,2000.0,NR,International TV Shows,166 min,Spanish,Description for title 5678
2,s2667,TV Show,Taare Zameen Par,David Fincher,India,2023-02-27 12:36:00,2010.0,PG-13,Horror Movies,5 Season,Hindi,Description for title 2667
3,s3346,TV Show,Kota Factory,Christopher Nolan,France,2024-03-08 21:54:27,2003.0,PG-13,International TV Shows,3 Seasons,English,Description for title 3346
4,s1138,Movie,The Gray Man,Rian Johnson,Spain,2023-07-10 05:02:47,1999.0,R,International TV Shows,141 min,Hindi,Description for title 1138
...,...,...,...,...,...,...,...,...,...,...,...,...
8895,s168,Movie,Piku 167,Anurag Kashyap,United Kingdom,2024-08-20 14:12:51,1993.0,PG,International TV Shows,148 min,Korean,Description for title 168
8896,s4833,Movie,Queen,Sanjay Leela Bhansali,Australia,2020-07-03 00:00:00,1994.0,TV-14,Thrillers,92 min,English,Description for title 4833
8897,s7833,Movie,Enola Holmes,Ava DuVernay,Australia,2022-11-02 20:55:12,2010.0,TV-14,Action & Adventure,89 min,Korean,Description for title 7833
8898,s2284,TV Show,Sacred Games,Anurag Kashyap,India,2022-09-23 23:17:20,2035.0,R,International TV Shows,5 Season,Korean,Description for title 2284
8899,s8800,TV Show,Dark,Ava DuVernay,France,2025-08-14 18:27:31,2020.0,R,Action & Adventure,4 Season,Spanish,Description for title 8800

Data Inspection

In [88]:
df.head(10)

,show_id,type,title,director,country,date_added,release_year,rating,listed_in,duration,language,description
0,s5219,TV Show,Red Notice,Anurag Kashyap,NaN,2019-12-08 20:01:50,1998.0,TV-G,Comedies,2 Seasons,NaN,Description for title 5219
1,s5678,Movie,Lagaan,Rian Johnson,South Korea,2024-09-23 13:00:57,2000.0,NR,International TV Shows,166 min,Spanish,Description for title 5678
2,s2667,TV Show,Taare Zameen Par,David Fincher,India,2023-02-27 12:36:00,2010.0,PG-13,Horror Movies,5 Season,Hindi,Description for title 2667
3,s3346,TV Show,Kota Factory,Christopher Nolan,France,2024-03-08 21:54:27,2003.0,PG-13,International TV Shows,3 Seasons,English,Description for title 3346
4,s1138,Movie,The Gray Man,Rian Johnson,Spain,2023-07-10 05:02:47,1999.0,R,International TV Shows,141 min,Hindi,Description for title 1138
5,s1414,Movie,Narcos,Ava DuVernay,Australia,2019-08-15 09:09:29,2015.0,PG-13,Documentaries,138 min,Korean,Description for title 1414
6,s2114,Movie,The Family Man,Sanjay Leela Bhansali,South Korea,2022-09-18 01:01:48,1997.0,G,Comedies,162 min,Hindi,Description for title 2114
7,s4135,Movie,The Family Man,Martin Scorsese,India,2020-08-22 02:05:09,1999.0,PG-13,Romantic Movies,70 min,Korean,Description for title 4135
8,s7346,Movie,RRR,Christopher Nolan,France,2024-08-21 16:46:31,2024.0,NR,Action & Adventure,122 min,English,Description for title 7346
9,s2101,tv show,Black Mirror,Sanjay Leela Bhansali,Australia,2020-09-13 16:56:21,2016.0,NR,Romantic Movies,85 min,Hindi,Description for title 2101

In [89]:
df.tail(10)

,show_id,type,title,director,country,date_added,release_year,rating,listed_in,duration,language,description
8890,s5687,Movie,The Witcher,Rian Johnson,United States,2019-01-14 01:10:01,1997.0,PG-13,Documentaries,132 min,Hindi,Description for title 5687
8891,s3447,Movie,Dangal,Sanjay Leela Bhansali,South Korea,2024-05-09 23:01:03,1992.0,NR,Action & Adventure,144 min,Korean,Description for title 3447
8892,s2876,TV Show,The Gray Man,Rajkumar Hirani,Germany,2020-07-25 13:47:49,1992.0,TV-PG,Drama,5 Season,Korean,Description for title 2876
8893,s8365,Movie,Sacred Games,Rajkumar Hirani,Spain,2018-03-07 02:17:33,1994.0,PG-13,Stand-Up Comedy,157 min,Hindi,Description for title 8365
8894,s5238,TV Show,Dark,Martin Scorsese,India,2023-01-13 02:48:42,2022.0,TV-PG,Stand-Up Comedy,7 Season,French,Description for title 5238
8895,s168,Movie,Piku 167,Anurag Kashyap,United Kingdom,2024-08-20 14:12:51,1993.0,PG,International TV Shows,148 min,Korean,Description for title 168
8896,s4833,Movie,Queen,Sanjay Leela Bhansali,Australia,2020-07-03 00:00:00,1994.0,TV-14,Thrillers,92 min,English,Description for title 4833
8897,s7833,Movie,Enola Holmes,Ava DuVernay,Australia,2022-11-02 20:55:12,2010.0,TV-14,Action & Adventure,89 min,Korean,Description for title 7833
8898,s2284,TV Show,Sacred Games,Anurag Kashyap,India,2022-09-23 23:17:20,2035.0,R,International TV Shows,5 Season,Korean,Description for title 2284
8899,s8800,TV Show,Dark,Ava DuVernay,France,2025-08-14 18:27:31,2020.0,R,Action & Adventure,4 Season,Spanish,Description for title 8800

In [90]:
df.shape

(8900, 12)

DataSet Information

In [91]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8900 entries, 0 to 8899
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8900 non-null   str
 1   type          8900 non-null   str
 2   title         8900 non-null   str
 3   director      8475 non-null   str
 4   country       8724 non-null   str
 5   date_added    8757 non-null   str
 6   release_year  8884 non-null   float64
 7   rating        8806 non-null   str
 8   listed_in     8900 non-null   str
 9   duration      8820 non-null   str
 10  language      8794 non-null   str
 11  description   8900 non-null   str
dtypes: float64(1), str(11)
memory usage: 834.5 KB

In [92]:
df.duplicated().sum()

np.int64(100)

In [93]:
df=df.drop_duplicates()
df

,show_id,type,title,director,country,date_added,release_year,rating,listed_in,duration,language,description
0,s5219,TV Show,Red Notice,Anurag Kashyap,NaN,2019-12-08 20:01:50,1998.0,TV-G,Comedies,2 Seasons,NaN,Description for title 5219
1,s5678,Movie,Lagaan,Rian Johnson,South Korea,2024-09-23 13:00:57,2000.0,NR,International TV Shows,166 min,Spanish,Description for title 5678
2,s2667,TV Show,Taare Zameen Par,David Fincher,India,2023-02-27 12:36:00,2010.0,PG-13,Horror Movies,5 Season,Hindi,Description for title 2667
3,s3346,TV Show,Kota Factory,Christopher Nolan,France,2024-03-08 21:54:27,2003.0,PG-13,International TV Shows,3 Seasons,English,Description for title 3346
4,s1138,Movie,The Gray Man,Rian Johnson,Spain,2023-07-10 05:02:47,1999.0,R,International TV Shows,141 min,Hindi,Description for title 1138
...,...,...,...,...,...,...,...,...,...,...,...,...
8895,s168,Movie,Piku 167,Anurag Kashyap,United Kingdom,2024-08-20 14:12:51,1993.0,PG,International TV Shows,148 min,Korean,Description for title 168
8896,s4833,Movie,Queen,Sanjay Leela Bhansali,Australia,2020-07-03 00:00:00,1994.0,TV-14,Thrillers,92 min,English,Description for title 4833
8897,s7833,Movie,Enola Holmes,Ava DuVernay,Australia,2022-11-02 20:55:12,2010.0,TV-14,Action & Adventure,89 min,Korean,Description for title 7833
8898,s2284,TV Show,Sacred Games,Anurag Kashyap,India,2022-09-23 23:17:20,2035.0,R,International TV Shows,5 Season,Korean,Description for title 2284
8899,s8800,TV Show,Dark,Ava DuVernay,France,2025-08-14 18:27:31,2020.0,R,Action & Adventure,4 Season,Spanish,Description for title 8800

In [94]:
df.duplicated().sum()

np.int64(0)

In [95]:
df.dtypes

show_id             str
type                str
title               str
director            str
country             str
date_added          str
release_year    float64
rating              str
listed_in           str
duration            str
language            str
description         str
dtype: object

In [96]:
df['date_added']=pd.to_datetime(df["date_added"])

Checking Missing Values

In [97]:
df.isnull().sum()

show_id           0
type              0
title             0
director        420
country         175
date_added      140
release_year     15
rating           93
listed_in         0
duration         80
language        105
description       0
dtype: int64

In [98]:
df['director'] = df['director'].fillna(df['director'].mode()[0])

In [99]:
df['country'] = df['country'].fillna(df['country'].mode()[0])

In [100]:
df['date_added'] = df['date_added'].fillna(df['date_added'].mode()[0])

Checking Numerical Outliers

In [101]:
for column in df.select_dtypes(include="number").columns:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[column] < lower) | (df[column] > upper)]

    print(column, "Outliers:", len(outliers))

release_year Outliers: 10

In [102]:
df['release_year'] = df['release_year'].fillna(df['release_year'].median())

In [103]:
df['rating'] = df['rating'].fillna(df['rating'].mode()[0])

In [104]:
df['duration'] = df['duration'].fillna(df['duration'].mode()[0])

In [105]:
df['language'] = df['language'].fillna(df['language'].mode()[0])

In [106]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
listed_in       0
duration        0
language        0
description     0
dtype: int64

In [107]:
df['release_year'] = df['release_year'].astype(int)

In [108]:
df.duplicated().sum()

np.int64(0)

Cleaned DataSet

In [109]:
df

,show_id,type,title,director,country,date_added,release_year,rating,listed_in,duration,language,description
0,s5219,TV Show,Red Notice,Anurag Kashyap,Australia,2019-12-08 20:01:50,1998,TV-G,Comedies,2 Seasons,French,Description for title 5219
1,s5678,Movie,Lagaan,Rian Johnson,South Korea,2024-09-23 13:00:57,2000,NR,International TV Shows,166 min,Spanish,Description for title 5678
2,s2667,TV Show,Taare Zameen Par,David Fincher,India,2023-02-27 12:36:00,2010,PG-13,Horror Movies,5 Season,Hindi,Description for title 2667
3,s3346,TV Show,Kota Factory,Christopher Nolan,France,2024-03-08 21:54:27,2003,PG-13,International TV Shows,3 Seasons,English,Description for title 3346
4,s1138,Movie,The Gray Man,Rian Johnson,Spain,2023-07-10 05:02:47,1999,R,International TV Shows,141 min,Hindi,Description for title 1138
...,...,...,...,...,...,...,...,...,...,...,...,...
8895,s168,Movie,Piku 167,Anurag Kashyap,United Kingdom,2024-08-20 14:12:51,1993,PG,International TV Shows,148 min,Korean,Description for title 168
8896,s4833,Movie,Queen,Sanjay Leela Bhansali,Australia,2020-07-03 00:00:00,1994,TV-14,Thrillers,92 min,English,Description for title 4833
8897,s7833,Movie,Enola Holmes,Ava DuVernay,Australia,2022-11-02 20:55:12,2010,TV-14,Action & Adventure,89 min,Korean,Description for title 7833
8898,s2284,TV Show,Sacred Games,Anurag Kashyap,India,2022-09-23 23:17:20,2035,R,International TV Shows,5 Season,Korean,Description for title 2284
8899,s8800,TV Show,Dark,Ava DuVernay,France,2025-08-14 18:27:31,2020,R,Action & Adventure,4 Season,Spanish,Description for title 8800